config/routes.rb
Rails.application.routes.draw do

  root 'static_notes#home'

  get '/home', to: 'static_notes#home'

  resources :notes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  
  def index
    @notes = Note.all
  end

  def show
    @notes = Note.find(params[:id])
  end

  def new
    @notes = Note.new
  end

  def create
    @notes = Note.new(notes_params)
 
    if @notes.save
      redirect_to notes_path
    else
      render :new
    end
  end
 
  def edit
    @notes = Note.find(params[:id])
  end

  def update
    @notes = Note.find(params[:id])
  
    if @notes.update(notes_params)
      redirect_to notes_path
    else
      render :edit
    end
  end

  def destroy
    Note.find(params[:id]).destroy
    redirect_to notes_path
  end

  private
 
    def notes_params
      params.require(:note).permit(:title, :body)
    end

end

app/controllers/static_notes_controller.rb
class StaticNotesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/static_notes_helper.rb
module StaticNotesHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', notes_path %>
<%= link_to 'Notes', notes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostItNoteApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/notes/edit.html.erb
<h1>Edit Note</h1>
<%= form_for @notes do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>
<% end %>

app/views/notes/index.html.erb
<h1> Notes Main </h1>
<% @notes.each do |note| %>
  <h2><%= note.title %></h2>
  <%= link_to 'Show', note_path(note.id) %>
  <%= link_to 'Edit', edit_note_path(note) %>
  <%= link_to 'Note', home_path %>
  <%= link_to 'New' , new_note_path %>
  <%= link_to 'Delete Note', note, method: :delete %>
<% end %>

app/views/notes/new.html.erb
<h1>New Note</h1>
<%= form_for @notes do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>
<% end %>

app/views/notes/show.html.erb
<h1><%= @notes.title %></h1>
<p><%= @notes.body %></p>
<%= link_to 'Back', notes_path %>

app/views/static_notes/about.html.erb
<%= link_to "View Notes", notes_path %>

app/views/static_notes/home.html.erb
i guess this is a home page? welcome home
<%= link_to "View Notes", notes_path %>